
create database luludb;

CREATE TABLE CUSTOMER_DATA_LULU (
  CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
  CUST_NAME VARCHAR(20) ,
  ADDRESS VARCHAR(120) ,
  EMAIL VARCHAR(60) NOT NULL,
  COUNTRY VARCHAR(20) ,
  PHONE VARCHAR(15) ,
  DATE_OF_BIRTH DATE ,
  USER_PWD VARCHAR(50) NOT NULL,
  INSERTED_DATE TIMESTAMP DEFAULT NOW(),
  primary key (CUSTOMER_ID)
);

ALTER TABLE CUSTOMER_DATA_LULU
ADD UNIQUE (EMAIL);


CREATE TABLE EMAIL_MASTER_LULU (
  USERNAME VARCHAR(30) ,
  PASSWORD VARCHAR(20) ,
  EMAIL_FROM VARCHAR(60),
  HOST VARCHAR(20) ,
  PORT VARCHAR(3) 
);

INSERT INTO EMAIL_MASTER_LULU
values ('ranjeeth.pt@gmail.com','XXXXXXXXXXXX','ranjeeth.pt@gmail.com','smtp.gmail.com','587');